services:
  clove-bot:
    build: .
    container_name: clove
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - clove-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  clove-network:
    driver: bridge

volumes:
  logs: